namespace OneToolkit.UI.Converters
{
    [bindable]
    [default_interface]
    runtimeclass BoolAsObjectConverter : Windows.UI.Xaml.Data.INotifyPropertyChanged, Windows.UI.Xaml.Data.IValueConverter
    {
        BoolAsObjectConverter();
        Object ValueForTrue;
        Object ValueForFalse;
    }
}
