import "IViewModel.idl";

namespace OneToolkit.UI.Converters
{
    [bindable]
    [default_interface]
    runtimeclass BoolAsObjectConverter : OneToolkit.Mvvm.IViewModel
    {
        BoolAsObjectConverter();
        Object ValueForTrue;
        Object ValueForFalse;
    }
}
