namespace OneToolkit.Storage
{
    runtimeclass NullBuffer : [default] Windows.Storage.Streams.IBuffer, Windows.Foundation.IMemoryBuffer {}

    [default_interface]
    static runtimeclass BufferHelper
    {
        [noexcept] static NullBuffer EmptyBuffer { get; };
        static UInt8 GetAt(Windows.Foundation.IMemoryBufferReference reference, UInt32 index);
        static void SetAt(Windows.Foundation.IMemoryBufferReference reference, UInt32 index, UInt8 value);
        static Boolean IsIndexValid(Windows.Foundation.IMemoryBufferReference reference, UInt32 index);
        [default_overload] static UInt8 GetAt(Windows.Storage.Streams.IBuffer buffer, UInt32 index);
        [default_overload] static void SetAt(Windows.Storage.Streams.IBuffer buffer, UInt32 index, UInt8 value);
        [default_overload] static Boolean IsIndexValid(Windows.Storage.Streams.IBuffer buffer, UInt32 index);
    }
}