namespace OneToolkit.UI.Converters
{
	interface IValueConverter
	{
		Object Convert(Object value, Windows.UI.Xaml.Interop.TypeName targetType, Object parameter, String language);
		Object ConvertBack(Object value, Windows.UI.Xaml.Interop.TypeName targetType, Object parameter, String language);
	};

	[default_interface]
	runtimeclass BoolReverseConverter : IValueConverter
	{
		BoolReverseConverter();
	}

	[default_interface]
	runtimeclass StringLocalizationConverter : IValueConverter
	{
		StringLocalizationConverter();
	}
}