namespace OneToolkit.UI.Converters
{
	[default_interface]
	runtimeclass NullToBoolConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		NullToBoolConverter();
	}

	[default_interface]
	runtimeclass VisibilityToOpacityConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		VisibilityToOpacityConverter();
	}

	[default_interface]
	runtimeclass BoolReverseConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		BoolReverseConverter();
	}

	[default_interface]
	runtimeclass StringTypeIdConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		StringTypeIdConverter();
	}

	[default_interface]
	runtimeclass StringVersionConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		StringVersionConverter();
	}

	[default_interface]
	runtimeclass StringFileSizeConverter : Windows.UI.Xaml.Data.IValueConverter, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		StringFileSizeConverter();
		Boolean UseBinaryPrefix;
	}

	[default_interface]
	runtimeclass StringLocalizationConverter : Windows.UI.Xaml.Data.IValueConverter, Windows.UI.Xaml.Data.INotifyPropertyChanged
	{
		StringLocalizationConverter();
		Windows.ApplicationModel.Resources.ResourceLoader Context;
	}

	[default_interface]
	runtimeclass StringToVisibilityConverter : Windows.UI.Xaml.Data.IValueConverter
	{
		StringToVisibilityConverter();
	}
}