import "IStorageItemHandle.idl";

namespace OneToolkit.Storage
{
    [flags]
    enum FileSharingMode
    {
        ShareNone = 0,
        ShareRead = 0x1,
        ShareWrite = 0x2,
        ShareDelete = 0x4
    };

    [default_interface]
    runtimeclass FileHandle : IStorageItemHandle
    {
        FileHandle(Windows.Storage.StorageFile file, Windows.Storage.FileAccessMode accessMode, FileSharingMode sharingMode);
        FileHandle(Windows.Storage.StorageFolder folder, String fileName, Windows.Storage.FileAccessMode accessMode, FileSharingMode sharingMode);
        UInt64 FileSize { get; };
        [noexcept] FileSharingMode SharingMode { get; };
        [noexcept] Windows.Storage.FileAccessMode AccessMode { get; };
    }
}