namespace OneToolkit.UI
{
    [default_interface]
    static runtimeclass Fonts
    {
        static String DefaultTextFontFamily { get; };
        static String DefaultIconFontFamily { get; };
        static IVectorView<String> SystemFontFamilies { get; };
    }
}