namespace OneToolkit.UI
{
    [default_interface]
    static runtimeclass FontHelper
    {
        static String DefaultIconFontFamily { get; };
        static IVectorView<String> GetInstalledFontFamilies();
    }
}