namespace OneToolkit.UI
{
    [default_interface]
    static runtimeclass FontHelper
    {
        static IVectorView<String> InstalledFontFamilies { get; };
        static Boolean IsFontFamilyPresent(String fontFamilyName);
    }
}