import "IAsyncClosable.idl";

namespace OneToolkit
{
	interface IAsyncSuspendable requires IAsyncClosable
	{
		Boolean IsSuspended { get; };
		Windows.Foundation.IAsyncAction SuspendAsync();
		Windows.Foundation.IAsyncAction ResumeAsync();
	};
}