namespace OneToolkit.Lifecycle
{
	delegate void EventHandlerWithSender(Object sender);

	interface ISuspendable
	{
		[noexcept] Boolean IsSuspended { get; };
		event EventHandlerWithSender Suspended;
		event EventHandlerWithSender Resumed;
	};

	interface IAsyncClosable requires Windows.Foundation.IClosable
	{
		event EventHandlerWithSender Closed;
		Windows.Foundation.IAsyncAction CloseAsync();
		Windows.Foundation.IAsyncOperation<Boolean> RequestCloseAsync();
	};

	interface IAsyncSuspendable requires ISuspendable
	{
		Windows.Foundation.IAsyncAction SuspendAsync();
		Windows.Foundation.IAsyncAction ResumeAsync();
	};
}