namespace OneToolkit
{
    enum LineEnding { CR, LF, CRLF };

    [default_interface]
    static runtimeclass LineEndingHelper
    {
        [noexcept] static String GetNewLineString(LineEnding ending);
        static String FormatLines(String[] lines, LineEnding ending);
        static String NormalizeLineEnding(String text, LineEnding ending);
    }
}
