namespace OneToolkit.Data.Text
{
    enum LineEnding
    {
        CR, LF, CRLF, Mixed
    };

    [default_interface]
    static runtimeclass LineEndingHelper
    {
        [noexcept] static String GetNewLineString(LineEnding lineEnding);
        static String NormalizeLineEnding(String text, LineEnding lineEnding);
    }
}