import "Lifecycle.idl";
import "IViewModel.idl";

namespace OneToolkit.Mvvm.NonGeneric
{
    [bindable]
    [default_interface]
    runtimeclass ObservableValue : OneToolkit.Mvvm.IViewModel, OneToolkit.Lifecycle.ICloneable
    {
        ObservableValue();
        ObservableValue(Object val);
        ObservableValue(Object val, Boolean suppressEvents);
        Object Value;
    }
}
