namespace OneToolkit.ApplicationModel
{
    [default_interface]
    static runtimeclass PackageVersionHelper
    {
        static String ToFormattedString(Windows.ApplicationModel.PackageVersion packageVersion);
        static Windows.ApplicationModel.PackageVersion FromFormattedString(String formattedString);
    }
}