namespace OneToolkit.Mvvm
{
    [default_interface]
    runtimeclass PropertyChangingEventArgs
    {
        PropertyChangingEventArgs(String propertyName);
        [noexcept] String PropertyName { get; };
    };
}