namespace OneToolkit.Runtime
{
    [default_interface]
    static runtimeclass Reflection
    {
        static Windows.UI.Xaml.Interop.TypeName GetTypeId(String typeName);
        static UInt64 GetSizeOf(Windows.UI.Xaml.Interop.TypeName typeId);
        static Object ActivateType(Windows.UI.Xaml.Interop.TypeName typeId);
        static String ExtractNamespace(Windows.UI.Xaml.Interop.TypeName typeId);
        static String GetMetadataFileLocation(Windows.UI.Xaml.Interop.TypeName typeId);
    }
}