namespace OneToolkit
{
    delegate Object SingletonInstanceProvider(Windows.UI.Xaml.Interop.TypeName typeId);
    
    [default_interface]
    static runtimeclass Singleton
    {
        static Object GetInstance(Windows.UI.Xaml.Interop.TypeName typeId);
        static Object GetInstance(Windows.UI.Xaml.Interop.TypeName typeId, SingletonInstanceProvider provider);
        static void SetInstance(Windows.UI.Xaml.Interop.TypeName typeId, Object value);
    }
}
