namespace OneToolkit.Storage
{
	[flags]
	enum HandleOptions
	{
		None = 0,
		OpenRequiringOplock = 0x40000,
		DeleteOnClose = 0x4000000,
		SequentialScan = 0x8000000,
		RandomAccess = 0x10000000,
		NoBuffering = 0x20000000,
		Overlapped = 0x40000000,
		WriteThrough = 0x80000000
	};

	[flags]
	enum HandleAccessOptions
	{
		None = 0,
		ReadAttributes = 0x80,
		Read = 0x120089,
		Write = 0x120116,
		Delete = 0x10000
	};

	[flags]
	enum HandleSharingOptions
	{
		ShareNone = 0,
		ShareRead = 0x1,
		ShareWrite = 0x2,
		ShareDelete = 0x4
	};

	enum HandleCreationOptions
	{
		CreateNew = 0x1,
		CreateAlways = 0x2,
		OpenExisting = 0x3,
		OpenAlways = 0x4,
		TruncateExisting = 0x5
	};
}