namespace OneToolkit.Data.Text
{
    [default_interface]
    static runtimeclass StringOperations
    {
        static String Trim(String text, String trimChars);
        static String TrimStart(String text, String trimChars);
        static String TrimEnd(String text, String trimChars);
        static String Replace(String text, String replaced, String replacedWith);
        static IVector<String> Split(String text, String delimiter);
    }
}