import "IViewModel.idl";

namespace OneToolkit.UI.Converters
{
    [bindable]
    [default_interface]
    runtimeclass StringLocalizationConverter : OneToolkit.Mvvm.IViewModel, Windows.UI.Xaml.Data.IValueConverter
    {
        StringLocalizationConverter();
        Windows.ApplicationModel.Resources.ResourceLoader Context;
    }
}