namespace OneToolkit.System
{
    struct ProcessorArchitectureInfo
    {
        Windows.System.ProcessorArchitecture SystemArchitecture;
        Windows.System.ProcessorArchitecture ProcessArchitecture;
    };

    [default_interface]
    static runtimeclass SystemInformation
    {
        static String DeviceName { get; };
        static String DeviceModel { get; };
        static String DeviceFamily { get; };
        static String DeviceManufacturer { get; };
        static ProcessorArchitectureInfo ArchitectureInfo { get; };
        static String OperatingSystemName { get; };
        static Windows.ApplicationModel.PackageVersion OperatingSystemVersion { get; };
        static Windows.Security.ExchangeActiveSyncProvisioning.EasClientDeviceInformation ClientDeviceInformation { get; };
    }
}