namespace OneToolkit.System
{

	[default_interface]
	runtimeclass OperatingSystemInfo
	{
		[noexcept] String Name { get; };
		[noexcept] Windows.ApplicationModel.PackageVersion Version { get; };
	}

    [default_interface]
    static runtimeclass SystemInformation
    {
        static String DeviceName { get; };
        static String DeviceModel { get; };
        static String DeviceFamily { get; };
        static String DeviceManufacturer { get; };
		static OperatingSystemInfo OperatingSystem { get; };
    }
}