namespace OneToolkit.Data
{
    enum Endianness
    {
        None, Little, Big
    };

    namespace Text
    {
        [default_interface]
        static runtimeclass TextEncodingHelper
        {
            static Boolean IsUtf8(Windows.Storage.Streams.IBuffer buffer);
            static Boolean IsUtf16(Windows.Storage.Streams.IBuffer buffer, out OneToolkit.Data.Endianness endianness);
            [noexcept] static UInt8 GetBomLength(Windows.Security.Cryptography.BinaryStringEncoding encoding);
            [noexcept] static Windows.Foundation.IReference<Windows.Security.Cryptography.BinaryStringEncoding> TryDetect(Windows.Storage.Streams.IBuffer buffer);
            [noexcept] static Windows.Foundation.IReference<Windows.Security.Cryptography.BinaryStringEncoding> TryDetectWithBom(Windows.Storage.Streams.IBuffer buffer);
        };
    }
}