import "ThemeConverter.idl";

namespace OneToolkit.UI.Theming
{
    [default_interface]
    runtimeclass ThemeService
    {
        RelativeTheme AppThemeOverride;
        AbsoluteTheme SystemAppsTheme { get; };
        AbsoluteTheme SystemShellTheme { get; };
		static ThemeService Current { get; };
    }
}