namespace OneToolkit.UI.Theming
{
	enum AbsoluteTheme
	{
		Light = 0,
		Dark = 1
	};

	enum RelativeTheme
	{
		Default = 0,
		Light = 1,
		Dark = 2
	};

	[default_interface]
	static runtimeclass RelativeThemeHelper
	{
		[noexcept] static AbsoluteTheme ToAbsoluteTheme(RelativeTheme theme, AbsoluteTheme defaultTheme);
	}

    [default_interface]
	runtimeclass ThemeService
	{
		AbsoluteTheme AppTheme { get; };
        RelativeTheme AppThemeOverride;
        AbsoluteTheme SystemAppsTheme { get; };
        AbsoluteTheme SystemShellTheme { get; };
		static ThemeService Current { get; };
    }
}