namespace OneToolkit.UI
{
    [default_interface]
    static runtimeclass ThemeHelper
    {
        static Windows.UI.Xaml.ApplicationTheme SystemAppsTheme { get; };
        static Windows.UI.Xaml.ApplicationTheme SystemShellTheme { get; };
    }
}