import "MetadataFile.idl";

namespace OneToolkit.Runtime
{
    delegate Object CustomTypeActivationHandler(TypeDetails typeInfo);

    [default_interface]
    runtimeclass TypeDetails
    {
        TypeDetails(Windows.UI.Xaml.Interop.TypeName typeId);
        [noexcept] Windows.UI.Xaml.Interop.TypeName Id { get; };
        [noexcept] String Name { get; };
        [noexcept] String Namespace { get; };
        [noexcept] Windows.UI.Xaml.Interop.TypeKind Kind { get; };
        [noexcept] String QualifiedName { get; };
        UInt64 BaseSize { get; };
        MetadataFile Metadata { get; };
        Object CreateInstance();
        [noexcept] static IVector<CustomTypeActivationHandler> CustomActivators { get; };
        static TypeDetails GetTypeDetails(Object value);
    }
}