import "Assembly.idl";

namespace OneToolkit.Runtime
{
    [default_interface]
    static runtimeclass TypeNameHelper
    {
        static String GetNamespace(Windows.UI.Xaml.Interop.TypeName typeName);
        static String GetDisplayName(Windows.UI.Xaml.Interop.TypeName typeName);
        static UInt64 GetBaseSize(Windows.UI.Xaml.Interop.TypeName typeName);
        static Assembly GetContainingAssembly(Windows.UI.Xaml.Interop.TypeName typeName);
        static Boolean IsGenericType(Windows.UI.Xaml.Interop.TypeName typeName);
    }
}