import "Window.idl";

namespace OneToolkit.UI.Windowing
{
	[default_interface]
	static runtimeclass ViewService
	{
		static IMapView<UInt64, IWindow> CachedViews { get; };
		static Windows.UI.ViewManagement.UserInteractionMode InteractionMode { get; };
		static IWindow CurrentWindow { get; };
		static IWindow GetWindowFromController(Object controller);
		static IWindowTitleBar GetTitleBarFromController(Object controller);
		static Windows.Foundation.IAsyncOperation<IVectorView<IWindow> > GetViewsAsync();
		static IWindow GetWindowFromId(UInt64 windowId);
	}
}