import "Lifecycle.idl";

namespace OneToolkit.UI
{
    interface IViewServiceProvider requires Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Title;
        Boolean IsFullScreen;
        Boolean IsDialogShown;
        Boolean ExtendsContentIntoTitleBar;
        Boolean IsTitleBarVisibile { get; };
        Int64 WindowHandle { get; };
        Windows.Foundation.Rect Bounds { get; };
        [noexcept] Object ReferenceSource { get; };
        Windows.UI.ViewManagement.UserInteractionMode InteractionMode { get; };
        void SetMinimumSize(Windows.Foundation.Size minSize);
        Windows.Foundation.IAsyncOperation<Boolean> CloseAsync();
    };

    [default_interface]
    static runtimeclass ViewService
    {
        static IViewServiceProvider GetForCurrentView();
        static IViewServiceProvider GetForWindowId(Int64 windowHandle);
    }
}