import "Lifecycle.idl";
import "IViewModel.idl";

namespace OneToolkit.UI
{
    interface IViewServiceProvider requires Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        String Title;
        Boolean IsFullScreen;
        Boolean ExtendViewIntoTitleBar;
        Int64 WindowHandle { get; };
        [noexcept] Object ReferenceSource { get; };
        Windows.Foundation.IAsyncOperation<Boolean> CloseAsync();
    };

    [default_interface]
    static runtimeclass ViewService
    {
        static IViewServiceProvider GetForCurrentView();
        static IViewServiceProvider GetForWindowId(Int64 windowHandle);
    }
}