import "Documentation.idl";
import "WindowTitleBar.idl";

namespace OneToolkit.UI.Windowing
{
	[OneToolkit.Metadata.Documentation.Summary("Represents a window.")]
	interface IWindow
	{
		String Title;
		Boolean IsVisible { get; };
		UInt64 Id { get; };
		UInt64 Handle { get; };
		Windows.Foundation.Rect Bounds { get; };
		IWindowTitleBar TitleBar { get; };
		Object Controller { get; };
		void Resize(Windows.Foundation.Size newSize);
		void SetMinimumSize(Windows.Foundation.Size minSize);
		Windows.Foundation.IAsyncAction CloseAsync();
		Windows.Foundation.IAsyncAction MinimizeAsync();
	};
}