import "Documentation.idl";

namespace OneToolkit.UI.Windowing
{
	[OneToolkit.Metadata.Documentation.Summary("Represents the title bar of a window.")]
	interface IWindowTitleBar
	{
		Double Height { get; };
		Boolean IsVisible { get; };
		Double LeftInset { get; };
		Double RightInset { get; };
		Object Controller { get; };
		Boolean ExtendsContentIntoTitleBar;
		Windows.Foundation.IReference<Windows.UI.Color> BackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ForegroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> InactiveBackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> InactiveForegroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonBackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonForegroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonHoverBackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonHoverForegroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonInactiveBackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonInactiveForegroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonPressedBackgroundColor;
		Windows.Foundation.IReference<Windows.UI.Color> ButtonPressedForegroundColor;
		void ResetToDefault();
	};
}