namespace OneToolkit.UI.Windowing
{
    [default_interface]
	runtimeclass WindowController
	{
		WindowController(Windows.UI.ViewManagement.ApplicationView appView, Windows.ApplicationModel.Core.CoreApplicationView coreAppView, Windows.UI.Core.SystemNavigationManager navigationManager, 
			Windows.UI.Core.Preview.SystemNavigationManagerPreview navigationManagerPreview);
		[noexcept] Windows.UI.ViewManagement.ApplicationView AppView { get; };
		[noexcept] Windows.ApplicationModel.Core.CoreApplicationView CoreAppView { get; };
		[noexcept] Windows.UI.Core.SystemNavigationManager NavigationManager { get; };
		[noexcept] Windows.UI.Core.Preview.SystemNavigationManagerPreview NavigationManagerPreview { get; };
    }
}