namespace OneToolkit.UI.Windowing
{
    [default_interface]
    runtimeclass WindowTitleBarController 
    {
        WindowTitleBarController(Windows.UI.ViewManagement.ApplicationViewTitleBar appViewTitleBar, Windows.ApplicationModel.Core.CoreApplicationViewTitleBar coreAppViewTitleBar);
		[noexcept] Windows.UI.ViewManagement.ApplicationViewTitleBar AppViewTitleBar { get; };
		[noexcept] Windows.ApplicationModel.Core.CoreApplicationViewTitleBar CoreAppViewTitleBar { get; };
    }
}