#include "XamlFramework/Base.idl"

namespace OneToolkit.UI.Xaml.Controls
{
    [default_interface]
    runtimeclass DescriptiveButton : XamlFramework.Controls.UserControl
	{
		DescriptiveButton();
		String Title;
		String Caption;
		Object Visuals;
		XamlFramework.Controls.Orientation Orientation;
		static XamlFramework.DependencyProperty TitleProperty { get; };
		static XamlFramework.DependencyProperty CaptionProperty { get; };
		static XamlFramework.DependencyProperty VisualsProperty { get; };
		static XamlFramework.DependencyProperty OrientationProperty { get; };
    }
}