#pragma once
#if __has_include(<winrt/Microsoft.UI.h>)
#define USE_WINUI3
#define XamlFramework Microsoft.UI.Xaml
#else
#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#define USE_WINUI2
#endif
#define USE_PLATFORM_XAML
#define XamlFramework Windows.UI.Xaml
#endif