#pragma once
#if __has_include(<winrt/Microsoft.UI.h>)
#define WINUI_VERSION 3
#define XamlFramework Microsoft.UI.Xaml
#else
#if __has_include(<winrt/Microsoft.UI.Xaml.h>)
#define WINUI_VERSION 2
#else
#define WINUI_VERSION 1
#endif
#define XamlFramework Windows.UI.Xaml
#endif