namespace Macros
{
	[attributeusage(target_runtimeclass, target_interface, target_struct, target_event, target_method, target_property)]
	attribute HeaderFileAttribute
	{
		String FileName;
	}

	[HeaderFile("OneToolkit.h")]
	struct DeclareEvent
	{

};
}